/var/www/vhosts/rockagenda.nl;
rm -rf httpdocs;
git clone https://github.com/sjerpbouwtsites/rockers-concertagenda httpdocs;
chown -R rockagenda:psacln httpdocs;
find httpdocs -type d -exec chmod 755 {} \;
find httpdocs -type f -exec chmod 644 {} \;
cd httpdocs;
npm run build;
npm install --legacy-peer-deps;
npm run build;