const unavailabilityTerms = [
  "uitgesteld",
  "verplaatst",
  "locatie gewijzigd",
  "besloten",
  "afgelast",
  "geannuleerd",
];

const tempFestivalNamesHACKDontHarvest = [
  "soulcrusher",
  "dynamo nachtmis",
  "home grown sessions",
  "calculating infinity 25th anniversary show",
];

const eventMetaTerms = [
  "show",
  `support:`,
  `support`,
  "album release party",
  "album release show",
  "album release",
  "special guest:",
  "special guest",
  "european tour",
  "world tour",
  "2024",
  "2025",
  "mmxxiv",
  "w/",
  "mmxxv",
  "en veel meer!",
  "en veel meer",
  "undefined",
  "+ meer",
  "and more",
  "met o.a.",
  "o.a. ",
  "undefined :",
  "met oa",
  "fanparty",
  " meer", // TODO dit wordt een probleem voor de band "MEERtalige henkies"
  ...tempFestivalNamesHACKDontHarvest,
];

/**
 * TODO om event types uit te kunnen sluiten moet nu forbidden terms gebruikt worden
 * moet eigen json met refusedEventTypes worden. 
 */
// const tempListOfForbiddenEventTypes = ["valkhof festival"]; // TODO is hack https://github.com/sjerpbouwtsites/rockers-concertagenda/issues/265

const forbiddenTerms = [
//  ...tempListOfForbiddenEventTypes,
  "afrobeats",
  "alternatieve rock",
  "americana",
  "americana",
  "art rock",
  "bieravond",
  "blaasrock",
  "boy band",
  "brass",
  "carnivore",
  "clubnacht",
  "countryrock",
  "dance-alle-dance",
  "dance-punk",
  "dance",
  "instrumental funk",
  "dream pop",
  "dream punk",
  "rap belge",
  "drill",
  "funk rock",
  "christian alternative rock",
  "dromerig",
  "electropop",
  "formula 1",
  "experi-metal",
  "conscious hip hop",
  "east coast hip hop",
  "fan event",
  "filmvertoning",
  "folkpunk",
  "funk-soul,pop",
  "global,pop",
  "house",
  "indie",
  "interactieve lezing",
  "jazz-core",
  "k-pop",
  "karaoke",
  "ldsports",
  "london calling",
  "mellow gold",
  "modern blues",
  "neofolk",
  "new french touch",
  "new romantic",
  "new wave",
  "piano rock",
  "poetry",
  "pop",
  "pubquiz",
  "punk-hop",
  "r&b",
  "rock-alternative",
  "schaakinstuif",
  "shoegaze",
  "singer-songwriter",
  "sophisti-pop",
  "trap",
  "uptempo",
  "VERBODENGENRE",
  "viral pop",
  "workshop",
  "australian hip hop",
  "dutch rap pop",
  "modern alternative rock",
  "open dag",
  "pov: indie",
  "quiz'm",
  "fanparty",
  "home grown sessions",
  "indietronica",
  "baroque pop",
  "chamber pop",
  "christian music",
];

const globalForbiddenGenres = [
  "drill",
  "dance",
  "indie",
  "dream",
  "shoegaze",
  "new-wave",
];

const globalGoodCategories = [
  "metal",
  "black",
  "crossover",
  "doom",
];

const wikipediaGoodGenres = [
  "[href$=metal]",
  "[href$=metal_music]",
  "[href=Hard_rock]",
  "[href=Acid_rock]",
  "[href=Death_rock]",
  "[href=Experimental_rock]",
  "[href=Garage_rock]",
  "[href=Hard_rock]",
  "[href=Post-rock]",
  "[href=Punk_rock]",
  "[href=Stoner_rock]",
  "[href=Hardcore_punk]",
  "[href=Skate_punk]",
  "[href=Street_punk]",
  "[href=Ska_punk]",
  "[href=Avant-garde_metal]",
  "[href=Extreme_metal]",
  "[href=Black_metal]",
  "[href=Death_metal]",
  "[href=Doom_metal]",
  "[href=Speed_metal]",
  "[href=Thrash_metal]",
  "[href=Glam_metal]",
  "[href=Groove_metal]",
  "[href=Power_metal]",
  "[href=Symphonic_metal]",
  "[href=Funk_metal]",
  "[href=Rap_metal]",
  "[href=Nu_metal]",
  "[href=Drone_metal]",
  "[href=Folk_metal]",
  "[href=Gothic_metal]",
  "[href=Post-metal]",
  "[href=Industrial_metal]",
  "[href=Neoclassical_metal]",
  "[href=Progressive_metal]",
  "[href=Sludge_metal]",
  "[href=Viking_metal]",
];

const goodCategories = [
  "black death",
  "melodic death metal",
  'brutal death metal',
  "death metal",
  "deathgrind",
  "blackened sludge",
  "balkan folk metal", 
  "romanian metal",
  "experimental black metal",
  "nyc metal",
  "technical black metal",
  "gothenburg metal",
  "melodic death metal",
  "metal",
  "folk metal",
  "swedish death metal",
  "gothic black metal",
  "gothic metal",
  "swedish melodeath",
  "usbm",
  "avant-garde metal",
  "brutal death metal",
  "grisly death metal",
  "new wave of osdm",
  "technical death metal",
  "deathcore",
  "downtempo deathcore",
  "slamming deathcore",
  "groove metal",
  "death metal",
  "metal noir",
  "egg punk",
  "black/death metal",
  "avant-garde black metal",
  "dissonant death metal",
  "nyc metal",
  "post-black metal",
  "dark post-punk",
  "sludge metal",
  "speed metal",
  "progressive sludge",
  "technical black metal",
  "voidgrind",
  "avant-garde",
  "technical black",
  "death metal",
  "voidgaze",
  "punk 'n' roll",
  "black/thrash metal",
  "blackened screamo",
  "powerviolence",
  "lowlands hardcore",
  "drone metal",
  "post-doom metal",
  "brutal deathcore",
  "viking volk",
  "psychedelic doom",
  "polish metalcore",
  "dark metal",
  "dark rock",
  "death metal",
  "deathcore",
  "djent",
  "doom",
  "dutch metal",
  "garage",
  "gothic metal",
  "gothic symphonic metal",
  "grindcore",
  "groove metal/metalcore",
  "hard rock",
  "hardcore punk",
  "hardcore",
  "heavy metal",
  "melodic death",
  "heavy psych",
  "heavy rock 'n roll",
  "heavy rock",
  "icelandic black metal",
  "icelandic metal",
  "industrial",
  "math rock",
  "melodic metalcore",
  "metal",
  "metalcore",
  "neue deutsche haerte",
  "neue deutsche harte",
  "noise",
  "nu metal",
  "pagan black metal",
  "post-black",
  "post-metal",
  "noise rock",
  "post-metal/rock (later)",
  "post-punk",
  "postpunk",
  "power metal",
  "psychobilly",
  "punk-emo-hardcore",
  "punk",
  "punx",
  "rockabilly, surf",
  "stoner",
  "surfpunkabilly",
  "symphonic metal",
  "thrash",
  "viking black metal",
  "viking/black metal (early)",
  "virginia metal",
  "war metal",
  "digital hardcore",
  "deathrash",
  "deathgrind",
  "brutal death metal",
];

export default {
  unavailability: unavailabilityTerms,
  forbidden: forbiddenTerms,
  globalForbiddenGenres,
  wikipediaGoodGenres,
  goodCategories,
  globalGoodCategories,
  eventMetaTerms,
};
